### ISSUE TITLE
Addon crashes at launch / playback

### ISSUE THREAD

**Issue by bangadrum** [matejdro/plugin.video.nebula#2]
Had been working fine, now crashes on launch. Have tried uninstalling and installing new download from master, but same issue.

Log as below:

2020-06-15 22:04:47.891 T:3011170912   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
2020-06-15 22:04:49.571 T:1934758768   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'NoneType' object has no attribute '__getitem__'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.nebula/main.py", line 127, in <module>
                                                router(dict(parse_qsl(sys.argv[2][1:])))
                                              File "/storage/.kodi/addons/plugin.video.nebula/main.py", line 108, in router
                                                api.login()
                                              File "/storage/.kodi/addons/plugin.video.nebula/nebulalib/api.py", line 50, in login
                                                user_data_body.json()["zype_auth_info"]["access_token"]
                                            TypeError: 'NoneType' object has no attribute '__getitem__'
                                            -->End of Python script error report<--
2020-06-15 22:04:49.765 T:2232415088   ERROR: GetDirectory - Error getting plugin://plugin.video.nebula/
2020-06-15 22:04:49.772 T:3011170912   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.nebula/) failed

**Comment by matejdro** [comment]
Something weird  is going with Nebula's auth system (sometimes I get the token, sometimes I don't). When this happens next time, can you try logging in to Nebula on the website and see if it helps?

**Comment by bangadrum** [comment]
Thanks for responding. It didn't work for a few days, then as you suggest started working again out out of the blue. I'll try as you suggest next time it fails. Thanks for the app - very useful.

**Comment by drewjc75** [comment]
In regard to bug #3: looks like logging out and back in on the website worked for Kodi playback. (Apologies for opening a duplicate, I didn't think the problem was the same because this one says "crashes at launch" and I thought that was when they opened the add-on, not attempted playback.)

**Comment by matejdro** [comment]
This issue should be fixed with https://github.com/matejdro/plugin.video.nebula/commit/2c6fb091e20db3fe33ef45c8a4f9756ceb2ac485.

Please reopen or comment on this issue if you still experience it after updating to latest version.
